apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    tier: frontend
spec:
  selector: 
    matchLabels: 
      tier: frontend
  template: 
    metadata:
      labels:
        tier: frontend
    spec: 
      containers:
      - name: my-nginx
        image: nginx:alpine
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2 #default is 1
          periodSeconds: 5 #default is 10
          failureThreshold: 1 # default is 3